name: ✨ Feature
description: 새로운 기능 추가 또는 기존 기능의 유의미한 개선
title: "[FEAT] "
labels: ["feat"]
body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Feature 이슈 가이드
        - 가급적 **사용자 스토리 + 수용 기준(AC)** 로 작성하세요.
        - 필요하면 아래 **Subtasks**를 이슈로 변환해 **양방향 연결**(Parent Task ↔ 하위 이슈)을 유지하세요.

  # 0) 상위 연결(선택)
  - type: input
    id: parent_task
    attributes:
      label: ↗️ Parent Task (선택)
      description: 상위 Task 이슈 번호(#42 형식)
      placeholder: "#42"

  # 1) 배경/문제
  - type: textarea
    id: context
    attributes:
      label: 🧩 배경·문제 정의
      description: 추가하고자 하는 기능의 필요성/이유
      placeholder: |
        - 현재 문제/기회는?
        - 왜 필요한가(비즈니스/사용자 관점)?
    validations:
      required: true

  # 2) 사용자 스토리
  - type: textarea
    id: user_story
    attributes:
      label: 👤 사용자 스토리
      description: 추가하고자 하는 기능의 사용자 관점에서의 설명
      placeholder: |
        - As a <role>, I want <capability> so that <benefit>.
        - 시나리오 예: GIVEN/WHEN/THEN ...

  # 3) 제안/대안
  - type: textarea
    id: proposal
    attributes:
      label: 💡 제안(설계 요약) & 대안
      description: 추가하고자 하는 기능의 설계 요약 및 대안
      placeholder: |
        - 제안: ...
        - 대안: ...
        - 트레이드오프: ...

  # 4) UX/화면 & 접근성
  - type: textarea
    id: ux
    attributes:
      label: 🖥️ UX/화면 설계 & 접근성
      description: 추가하고자 하는 기능의 UX/화면 설계 및 접근성 고려사항
      placeholder: |
        - 와이어프레임/디자인 링크
        - a11y: 키보드 내비게이션, 대비, ARIA 등

  # 5) API/데이터 영향
  - type: textarea
    id: api_data
    attributes:
      label: 🔗 API/데이터 모델 영향
      description: 추가하고자 하는 기능의 API/데이터 영향
      placeholder: |
        - API 신규/변경(엔드포인트·스키마·에러코드)
        - DB/캐시/마이그레이션
        - 성능·보안·비용 영향

  # 6) 스프린트/마일스톤
  - type: input
    id: milestone
    attributes:
      label: 🗓️ 마일스톤/스프린트 (선택)
      description: 이름 규칙 예시: 2025-09 Sprint 1 / v0.3.0 / 2025-W36
      placeholder: 2025-09 Sprint 1
  - type: input
    id: start_date
    attributes:
      label: 시작일(YYYY-MM-DD, 선택)
      description: "날짜 형식은 YYYY-MM-DD 로 작성"
      placeholder: 2025-09-01
  - type: input
    id: due_date

    attributes:
      label: 종료일(YYYY-MM-DD, 선택)
      description: "날짜 형식은 YYYY-MM-DD 로 작성"
      placeholder: 2025-09-15

  # 7) 우선순위/규모/도메인
  - type: dropdown
    id: priority
    attributes:
      label: 🚦 우선순위
      options: [P0-urgent, P1-high, P2-med, P3-low]
  - type: dropdown
    id: domain
    attributes:
      label: 🧭 도메인(복수 선택)
      multiple: true
      options: [frontend, backend, infra, design, docs, auth, explore, review, mypage]

  # 8) 수용 기준(AC) & 완료 정의(DoD)
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: ✅ 수용 기준(AC)
      placeholder: |
        - [ ] GIVEN/WHEN/THEN 형태로 테스트 가능한 문장
        - [ ] p95 응답 < 300ms (if BE)
  - type: checkboxes
    id: dod
    attributes:
      label: 🧾 완료 정의(DoD)
      options:
        - label: 테스트 통과 및 커버리지 기준 충족
        - label: 문서/ADR/CHANGELOG 반영
        - label: 라벨/연결(Closes/Fixes) 정리
        - label: 관측(로그/모니터링/알람) 확인

  # 9) Subtasks
  - type: textarea
    id: subtasks
    attributes:
      label: 🧩 Subtasks (체크리스트 → 이슈 전환 권장)
      placeholder: |
        - [ ] FE: 컴포넌트/상태관리
        - [ ] BE: API/스키마
        - [ ] TEST: 단위/통합/E2E
        - [ ] DOCS: 사용자/개발 문서
