# .github/ISSUE_TEMPLATE/03_refactor.yml
name: ♻️ Refactor
description: 코드 품질/구조/성능/안정성 개선 (기능 변화 최소화)
title: "[REFACTOR] "
labels: ["refactor"]
body:
  - type: markdown
    attributes:
      value: |
        ## ♻️ 리팩토링 가이드
        - **기능 동작은 동일**, 품질/구조/성능을 개선합니다.
        - 영향 범위, 성능/안정성 리스크, 롤백/검증 계획을 명확히 하세요.
        - 하위 작업이 필요하면 아래 Subtasks를 이슈로 변환하고 **양방향 연결**하세요.

  # 0) 상위 연결(선택)
  - type: input
    id: parent_task
    attributes:
      label: ↗️ Parent Task (선택)
      description: 상위 Task 이슈 번호(#42 형식)
      placeholder: "#42"
  - type: input
    id: related_bug
    attributes:
      label: 🐛 관련 Bug 이슈 (선택)
      description: 이 리팩토링의 계기가 된 Bug 이슈 번호(#42 형식)
      placeholder: "#42"
  - type: checkboxes
    id: refactor_trigger
    attributes:
      label: 🎯 리팩토링 계기
      options:
        - label: 🐛 Bug 수정 과정에서 발견된 구조적 문제
        - label: 📊 성능 이슈 해결 필요
        - label: 🧪 테스트 어려움/커버리지 부족
        - label: 🔄 코드 중복/복잡도 개선
        - label: 📝 기술 부채 정리
        - label: 🔧 새 요구사항 대비 구조 개선

  # 1) 대상/현황/문제
  - type: textarea
    id: target_scope
    attributes:
      label: 🎯 대상·범위
      description: 파일/모듈/레이어/경로 등 구체적으로 명시
      placeholder: |
        예) FE: src/components/Table/*
            BE: app.user.service.*, repository.*, /v1/users/*
    validations:
      required: true
  - type: textarea
    id: current_issues
    attributes:
      label: 🧩 현재 문제/악취(Code Smell)
      description: 복잡도/중복/결합도/응집도/성능/메모리/테스트 취약점 등
      placeholder: |
        - 중복 쿼리로 p95 900ms 초과
        - 거대 컴포넌트(> 600 LOC)로 변경 비용↑/테스트 어려움

  # 2) 개선 목표 & 수용 기준(AC)
  - type: textarea
    id: goals
    attributes:
      label: 🎯 개선 목표
      placeholder: |
        - p95 응답 900ms → 300ms 이하
        - 순환 의존 제거, 파일당 LOC < 300
  - type: textarea
    id: ac
    attributes:
      label: ✅ 수용 기준(AC)
      description: 테스트 가능한 문장/숫자 기준 권장
      placeholder: |
        - [ ] 동일 입력 대비 출력/사이드이펙트가 기존과 동일함(회귀 없음)
        - [ ] p95 < 300ms (@/users?filter=active)
        - [ ] Unit 커버리지 > 70%, 변경 라인 diff 커버리지 > 90%
        - [ ] 번들 사이즈 -15% (FE), 할당 메모리 -20% (BE)
    validations:
      required: true

  # 3) 설계/전략
  - type: textarea
    id: approach
    attributes:
      label: 🧠 접근 전략
      placeholder: |
        - 모듈 분리(Ports/Adapters), 의존 역전, 트랜잭션 경계 재조정
        - 캐시 레이어 도입(Upstash/Redis), N+1 제거, 인덱스 최적화
        - FE 상태 분리, 메모이제이션, 가상 스크롤
  - type: checkboxes
    id: tradeoffs
    attributes:
      label: ⚖️ 트레이드오프/리스크
      options:
        - label: 성능/메모리/비용 영향 가능
        - label: 마이그레이션/데이터 정합성 이슈 가능
        - label: 병렬 작업과 충돌 가능(머지 리스크)

  # 4) 검증/롤백/관측
  - type: textarea
    id: verification
    attributes:
      label: 🔍 검증 계획
      placeholder: |
        - 단위/슬라이스/통합/E2E 테스트
        - 성능 측정 시나리오 및 샘플 데이터(고정 seed)
        - A/B 또는 Shadow 트래픽
  - type: textarea
    id: rollback
    attributes:
      label: ↩️ 롤백 전략
      placeholder: |
        - Feature flag/Env toggle
        - Canary → 점진 배포 → 전체 전개
  - type: textarea
    id: observability
    attributes:
      label: 📈 관측/알람
      placeholder: |
        - 로그/메트릭/트레이싱 지표 및 임계값
        - 알람 룰(에러율, p95, 고루틴/스레드/큐 적체 등)

  # 5) 일정/우선순위/도메인
  - type: input
    id: milestone
    attributes:
      label: 🗓️ 마일스톤/스프린트 (선택)
      placeholder: 2025-09 Sprint 1
  - type: dropdown
    id: priority
    attributes:
      label: 🚦 우선순위
      options: [P0-urgent, P1-high, P2-med, P3-low]
  - type: dropdown
    id: domain
    attributes:
      label: 🧭 도메인(복수 선택)
      multiple: true
      options: [frontend, backend, infra, design, docs, auth, explore, review, mypage]

  # 6) Subtasks
  - type: textarea
    id: subtasks
    attributes:
      label: 🧩 Subtasks (체크리스트 → 이슈 전환 권장)
      placeholder: |
        - [ ] 리포지토리 계층 분리 # 
        - [ ] 쿼리 최적화/인덱스 추가 #
        - [ ] 캐시 미스/적중률 모니터링 대시보드 #
      description: Convert to issue로 개별 이슈 생성 후 이 항목에 #번호 연결

  # 7) 참고
  - type: textarea
    id: refs
    attributes:
      label: 🔗 참고/연관 이슈·PR·문서
      placeholder: |
        - #123, #456 / ADR 링크 / 성능 리포트 / 디자인 링크
