# .github/ISSUE_TEMPLATE/09_basic.yml
name: 🧾 Basic
description: Task/마일스톤과 무관한 일반 이슈 (아이디어·경량 개선·간단 요청 등)
title: "[BASIC] "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🧾 Basic 이슈 가이드
        - 빠르게 제안/토론하고 싶은 아이디어, 경량 개선, 가벼운 요청에 사용하세요.
        - 필요 시 다른 템플릿(Feature/Bug/Refactor/Chore 등)으로 승격 가능.

  # 0) Parent Task 연결 (선택)
  - type: input
    id: parent_task
    attributes:
      label: ↗️ Parent Task (선택)
      placeholder: "#42"

  # 1) 요약 & 설명
  - type: input
    id: summary
    attributes:
      label: 🔎 요약(한 줄)
      placeholder: 예) 버튼 hover 색상 제안
  - type: textarea
    id: description
    attributes:
      label: 📄 상세 설명
      placeholder: |
        - 배경/문제: ...
        - 제안/개선: ...
        - 기대효과: ...

  # 2) 수용 기준(AC)
  - type: textarea
    id: ac
    attributes:
      label: ✅ 수용 기준(AC)
      placeholder: |
        - [ ] hover 시 WCAG AA 대비 충족
        - [ ] 다크/라이트 모드 일관성

  # 3) 우선순위/도메인
  - type: dropdown
    id: priority
    attributes:
      label: 🚦 우선순위
      options: [P0-urgent, P1-high, P2-med, P3-low]
  - type: dropdown
    id: domain
    attributes:
      label: 🧭 도메인(복수 선택 가능)
      multiple: true
      options: [frontend, backend, infra, design, docs, auth, explore, review, mypage]

  # 4) 체크리스트
  - type: textarea
    id: checklist
    attributes:
      label: 🧩 체크리스트
      placeholder: |
        - [ ] 영향 범위 확인
        - [ ] UI/UX 확인
        - [ ] 관련자 리뷰
        - [ ] 문서 반영

  # 5) 참고
  - type: textarea
    id: refs
    attributes:
      label: 🔗 참고/연관 자료
      placeholder: |
        - 스크린샷, 디자인, 커밋, 외부 링크
