# .github/ISSUE_TEMPLATE/3_refactor.yml
name: ♻️ Refactor
description: 코드 리팩토링 또는 구조 개선
title: '[REFACTOR] '
labels: ['refactor']
body:
  - type: markdown
    attributes:
      value: |
        ## ♻️ 리팩토링 제안
        성능 개선, 가독성 향상, 구조적 개선 등 리팩토링이 필요한 영역을 설명해주세요.
  - type: textarea
    id: target
    attributes:
      label: 리팩토링 대상
      description: 어떤 파일, 모듈, 컴포넌트가 개선 대상인가요?
      placeholder: 예: `src/components/Button.tsx`, `api/user.ts` 등
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: 리팩토링 이유
      description: 왜 리팩토링이 필요한지 설명해주세요.
      placeholder: 코드가 복잡하거나 중복되어 유지보수가 어렵기 때문 등
    validations:
      required: true
  - type: textarea
    id: direction
    attributes:
      label: 개선 방향
      description: 예상하는 리팩토링 방식이나 전략을 간단히 설명해주세요.
      placeholder: 컴포넌트 분리, 로직 추출, 네이밍 정
