name: Feature Test
description: Simple feature template for testing
title: "[FEAT] "
labels: ["feature"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What feature should be added?
    validations:
      required: true
