name: Notion Sync (Docs)
on:
  push:
    branches: [main]
    paths: ['ADR/**', 'CHANGELOG.md']
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract latest ADR title
        id: meta
        run: |
          FILE=$(git diff --name-only HEAD~1 HEAD | grep -E '^ADR/.+\.md$' || true)
          if [ -n "$FILE" ]; then
            TITLE=$(head -n 1 "$FILE" | sed 's/^# //')
          else
            TITLE="CHANGELOG Update"
          fi
          echo "title=$TITLE" >> $GITHUB_OUTPUT
      - name: Send to Notion (ADR DB)
        if: ${{ steps.meta.outputs.title != '' }}
        run: |
          curl -sS -X POST "https://api.notion.com/v1/pages" \
            -H "Authorization: Bearer ${{ secrets.NOTION_TOKEN }}" \
            -H "Content-Type: application/json" \
            -H "Notion-Version: 2022-06-28" \
            --data @- << 'JSON'
          {
            "parent": { "database_id": "${{ vars.NOTION_DATABASE_ID_ADR }}" },
            "properties": {
              "Name": { "title": [{"text": {"content": "${{ steps.meta.outputs.title }}"}}] },
              "GitHubURL": { "url": "${{ github.server_url }}/${{ github.repository }}" }
            }
          }
JSON
